set(MP4 "$ENV{K230_SDK_ROOT}/src/common/cdk/user/middleware/mp4_format")
set(MP4_OUT "${CMAKE_CURRENT_BINARY_DIR}/sdk-mp4")
file(MAKE_DIRECTORY "${MP4_OUT}/source")
file(GLOB mov_files "${MP4}/src/libmov/source/*.c" "${MP4}/src/libmov/source/*.h")
foreach(input ${mov_files})
    get_filename_component(name "${input}" NAME)
    file(READ "${input}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    file(WRITE "${MP4_OUT}/source/${name}" "${content}")
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/../patches/mp4-end-time.cmake")
file(GLOB mov_sources "${MP4_OUT}/source/*.c")
file(GLOB flv_sources "${MP4}/src/libflv/source/*.c")
add_library(sdk_mp4 STATIC ${mov_sources} ${flv_sources})
target_include_directories(sdk_mp4 SYSTEM PUBLIC "${MP4}/src/libmov/include" "${MP4}/src/libflv/include")
